[2022-02-12 15:41:14,820] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_3 2022-02-11T00:00:00+00:00 [queued]>
[2022-02-12 15:41:14,833] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_3 2022-02-11T00:00:00+00:00 [queued]>
[2022-02-12 15:41:14,833] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 15:41:14,834] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-02-12 15:41:14,836] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 15:41:14,854] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2022-02-11T00:00:00+00:00
[2022-02-12 15:41:14,861] {standard_task_runner.py:52} INFO - Started process 359 to run task
[2022-02-12 15:41:14,864] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_rule', 'task_3', '2022-02-11T00:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule.py', '--cfg-path', '/tmp/tmpcxto6y84', '--error-file', '/tmp/tmpso0fcjn2']
[2022-02-12 15:41:14,868] {standard_task_runner.py:77} INFO - Job 5: Subtask task_3
[2022-02-12 15:41:14,939] {logging_mixin.py:104} INFO - Running <TaskInstance: trigger_rule.task_3 2022-02-11T00:00:00+00:00 [running]> on host 02a866e7b1b6
[2022-02-12 15:41:15,014] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_rule
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-02-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-11T00:00:00+00:00
[2022-02-12 15:41:15,015] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-02-12 15:41:15,016] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'exit 0']
[2022-02-12 15:41:15,023] {subprocess.py:75} INFO - Output:
[2022-02-12 15:41:15,025] {subprocess.py:83} INFO - Command exited with return code 0
[2022-02-12 15:41:15,042] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=trigger_rule, task_id=task_3, execution_date=20220211T000000, start_date=20220212T154114, end_date=20220212T154115
[2022-02-12 15:41:15,083] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-12 15:41:15,119] {local_task_job.py:151} INFO - Task exited with return code 0
